/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddDirectoryBody {
    /// The name of the directory
    #[serde(rename = "name")]
    pub name: String,
    /// mnemonics are human readable unique identifiers for datasets mnemonics have the form <random adjective>_<random first name>
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    /// A custom searchable tag for the directory
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}

impl AddDirectoryBody {
    pub fn new(name: String) -> AddDirectoryBody {
        AddDirectoryBody {
            name,
            parent: None,
            tag: None,
        }
    }
}

