/*
 * dabih-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Chunk {
    /// The database id of the chunk
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<serde_json::Value>,
    /// The id of the data the chunk belongs to
    #[serde(rename = "dataId", deserialize_with = "Option::deserialize")]
    pub data_id: Option<serde_json::Value>,
    /// The SHA-256 hash of the unencrypted chunk data base64url encoded
    #[serde(rename = "hash")]
    pub hash: String,
    /// The AES-256 initialization vector base64url encoded
    #[serde(rename = "iv")]
    pub iv: String,
    /// The start of the chunk as a byte position in the file
    #[serde(rename = "start", deserialize_with = "Option::deserialize")]
    pub start: Option<serde_json::Value>,
    /// The end of the chunk as a byte position in the file
    #[serde(rename = "end", deserialize_with = "Option::deserialize")]
    pub end: Option<serde_json::Value>,
    /// The CRC32 checksum of the encrypted chunk data base64url encoded
    #[serde(rename = "crc", deserialize_with = "Option::deserialize")]
    pub crc: Option<String>,
    /// chunk creation timestamp
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// chunk last update timestamp
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl Chunk {
    pub fn new(id: Option<serde_json::Value>, data_id: Option<serde_json::Value>, hash: String, iv: String, start: Option<serde_json::Value>, end: Option<serde_json::Value>, crc: Option<String>, created_at: String, updated_at: String) -> Chunk {
        Chunk {
            id,
            data_id,
            hash,
            iv,
            start,
            end,
            crc,
            created_at,
            updated_at,
        }
    }
}

