/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.0.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DabihInfoBrandingOrganization {
    #[serde(rename = "logo")]
    pub logo: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl DabihInfoBrandingOrganization {
    pub fn new(logo: String, url: String, name: String) -> DabihInfoBrandingOrganization {
        DabihInfoBrandingOrganization {
            logo,
            url,
            name,
        }
    }
}

