/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DabihInfo {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "branding")]
    pub branding: Box<models::DabihInfoBranding>,
}

impl DabihInfo {
    pub fn new(version: String, branding: models::DabihInfoBranding) -> DabihInfo {
        DabihInfo {
            version,
            branding: Box::new(branding),
        }
    }
}

