/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DabihInfoBranding {
    #[serde(rename = "organization")]
    pub organization: Box<models::DabihInfoBrandingOrganization>,
    #[serde(rename = "department")]
    pub department: Box<models::DabihInfoBrandingOrganization>,
    #[serde(rename = "contact")]
    pub contact: Box<models::DabihInfoBrandingContact>,
    #[serde(rename = "admin")]
    pub admin: Box<models::DabihInfoBrandingAdmin>,
}

impl DabihInfoBranding {
    pub fn new(organization: models::DabihInfoBrandingOrganization, department: models::DabihInfoBrandingOrganization, contact: models::DabihInfoBrandingContact, admin: models::DabihInfoBrandingAdmin) -> DabihInfoBranding {
        DabihInfoBranding {
            organization: Box::new(organization),
            department: Box::new(department),
            contact: Box::new(contact),
            admin: Box::new(admin),
        }
    }
}

