/*
 * dabih-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DabihInfoBrandingAdmin {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl DabihInfoBrandingAdmin {
    pub fn new(email: String, name: String) -> DabihInfoBrandingAdmin {
        DabihInfoBrandingAdmin {
            email,
            name,
        }
    }
}

