/*
 * dabih-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DabihInfoBrandingContact {
    #[serde(rename = "phone")]
    pub phone: String,
    #[serde(rename = "country")]
    pub country: String,
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "city")]
    pub city: String,
    #[serde(rename = "zip")]
    pub zip: String,
    #[serde(rename = "street")]
    pub street: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl DabihInfoBrandingContact {
    pub fn new(phone: String, country: String, state: String, city: String, zip: String, street: String, email: String, name: String) -> DabihInfoBrandingContact {
        DabihInfoBrandingContact {
            phone,
            country,
            state,
            city,
            zip,
            street,
            email,
            name,
        }
    }
}

