/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileDownload {
    /// The database id of the inode
    #[serde(rename = "id")]
    pub id: String,
    /// mnemonics are human readable unique identifiers for datasets mnemonics have the form <random adjective>_<random first name>
    #[serde(rename = "mnemonic")]
    pub mnemonic: String,
    /// The type of the inode
    #[serde(rename = "type")]
    pub r#type: u32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tag", deserialize_with = "Option::deserialize")]
    pub tag: Option<String>,
    /// The database id file data if the inode is a file
    #[serde(rename = "dataId")]
    pub data_id: String,
    #[serde(rename = "data")]
    pub data: Box<models::ChunkData>,
    #[serde(rename = "parentId", deserialize_with = "Option::deserialize")]
    pub parent_id: Option<serde_json::Value>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "keys")]
    pub keys: Vec<models::Key>,
}

impl FileDownload {
    pub fn new(id: String, mnemonic: String, r#type: u32, name: String, tag: Option<String>, data_id: String, data: models::ChunkData, parent_id: Option<serde_json::Value>, created_at: String, updated_at: String, keys: Vec<models::Key>) -> FileDownload {
        FileDownload {
            id,
            mnemonic,
            r#type,
            name,
            tag,
            data_id,
            data: Box::new(data),
            parent_id,
            created_at,
            updated_at,
            keys,
        }
    }
}

