/*
 * dabih-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileData {
    /// The database id of the file data
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<serde_json::Value>,
    #[serde(rename = "uid")]
    pub uid: String,
    #[serde(rename = "createdBy")]
    pub created_by: String,
    #[serde(rename = "fileName")]
    pub file_name: String,
    #[serde(rename = "filePath", deserialize_with = "Option::deserialize")]
    pub file_path: Option<String>,
    #[serde(rename = "hash", deserialize_with = "Option::deserialize")]
    pub hash: Option<String>,
    /// The size of the file in bytes
    #[serde(rename = "size", deserialize_with = "Option::deserialize")]
    pub size: Option<serde_json::Value>,
    #[serde(rename = "keyHash")]
    pub key_hash: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl FileData {
    pub fn new(id: Option<serde_json::Value>, uid: String, created_by: String, file_name: String, file_path: Option<String>, hash: Option<String>, size: Option<serde_json::Value>, key_hash: String, created_at: String, updated_at: String) -> FileData {
        FileData {
            id,
            uid,
            created_by,
            file_name,
            file_path,
            hash,
            size,
            key_hash,
            created_at,
            updated_at,
        }
    }
}

