/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct File {
    /// The database id of the inode
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "mnemonic")]
    pub mnemonic: String,
    /// The type of the inode
    #[serde(rename = "type")]
    pub r#type: u32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tag", deserialize_with = "Option::deserialize")]
    pub tag: Option<String>,
    #[serde(rename = "data")]
    pub data: Box<models::FileData>,
    #[serde(rename = "parentId", deserialize_with = "Option::deserialize")]
    pub parent_id: Option<serde_json::Value>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl File {
    pub fn new(id: String, mnemonic: String, r#type: u32, name: String, tag: Option<String>, data: models::FileData, parent_id: Option<serde_json::Value>, created_at: String, updated_at: String) -> File {
        File {
            id,
            mnemonic,
            r#type,
            name,
            tag,
            data: Box::new(data),
            parent_id,
            created_at,
            updated_at,
        }
    }
}

