/*
 * dabih-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Healthy200Response {
    #[serde(rename = "healthy")]
    pub healthy: bool,
}

impl Healthy200Response {
    pub fn new(healthy: bool) -> Healthy200Response {
        Healthy200Response {
            healthy,
        }
    }
}

