/*
 * dabih-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InodeMembers {
    /// The database id of the inode
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<serde_json::Value>,
    #[serde(rename = "mnemonic")]
    pub mnemonic: String,
    #[serde(rename = "type")]
    pub r#type: models::InodeType,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tag", deserialize_with = "Option::deserialize")]
    pub tag: Option<String>,
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<Box<models::FileData>>>,
    #[serde(rename = "parentId", deserialize_with = "Option::deserialize")]
    pub parent_id: Option<serde_json::Value>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "members")]
    pub members: Vec<models::Member>,
}

impl InodeMembers {
    pub fn new(id: Option<serde_json::Value>, mnemonic: String, r#type: models::InodeType, name: String, tag: Option<String>, parent_id: Option<serde_json::Value>, created_at: String, updated_at: String, members: Vec<models::Member>) -> InodeMembers {
        InodeMembers {
            id,
            mnemonic,
            r#type,
            name,
            tag,
            data: None,
            parent_id,
            created_at,
            updated_at,
            members,
        }
    }
}

