/*
 * dabih-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Job {
    #[serde(rename = "jobId")]
    pub job_id: String,
    #[serde(rename = "status")]
    pub status: models::JobStatus,
}

impl Job {
    pub fn new(job_id: String, status: models::JobStatus) -> Job {
        Job {
            job_id,
            status,
        }
    }
}

