/*
 * dabih-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Key {
    /// The database id of the key
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<serde_json::Value>,
    /// The inode id the key belongs to
    #[serde(rename = "inodeId", deserialize_with = "Option::deserialize")]
    pub inode_id: Option<serde_json::Value>,
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl Key {
    pub fn new(id: Option<serde_json::Value>, inode_id: Option<serde_json::Value>, hash: String, key: String, created_at: String, updated_at: String) -> Key {
        Key {
            id,
            inode_id,
            hash,
            key,
            created_at,
            updated_at,
        }
    }
}

