/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Key {
    /// The database id of the key
    #[serde(rename = "id")]
    pub id: String,
    /// The inode id the key belongs to
    #[serde(rename = "inodeId")]
    pub inode_id: String,
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl Key {
    pub fn new(id: String, inode_id: String, hash: String, key: String, created_at: String, updated_at: String) -> Key {
        Key {
            id,
            inode_id,
            hash,
            key,
            created_at,
            updated_at,
        }
    }
}

