/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.0.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyEnableBody {
    /// The user the key belongs to
    #[serde(rename = "sub")]
    pub sub: String,
    /// The hash of the key
    #[serde(rename = "hash")]
    pub hash: String,
    /// The key status to set
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl KeyEnableBody {
    pub fn new(sub: String, hash: String, enabled: bool) -> KeyEnableBody {
        KeyEnableBody {
            sub,
            hash,
            enabled,
        }
    }
}

