/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyRemoveBody {
    /// The user the key belongs to
    #[serde(rename = "sub")]
    pub sub: String,
    /// The hash of the key
    #[serde(rename = "hash")]
    pub hash: String,
}

impl KeyRemoveBody {
    pub fn new(sub: String, hash: String) -> KeyRemoveBody {
        KeyRemoveBody {
            sub,
            hash,
        }
    }
}

