/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.0.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyAddBody {
    /// The user the key should belong to
    #[serde(rename = "sub")]
    pub sub: String,
    #[serde(rename = "data")]
    pub data: models::CryptoPeriodJsonWebKey,
    /// If true the key is a root key, used to decrypt all datasets
    #[serde(rename = "isRootKey")]
    pub is_root_key: bool,
}

impl KeyAddBody {
    pub fn new(sub: String, data: models::CryptoPeriodJsonWebKey, is_root_key: bool) -> KeyAddBody {
        KeyAddBody {
            sub,
            data,
            is_root_key,
        }
    }
}

