/*
 * dabih-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListResponse {
    /// The list of parent directories
    #[serde(rename = "parents")]
    pub parents: Vec<models::InodeMembers>,
    /// The list of inodes in the directory
    #[serde(rename = "children")]
    pub children: Vec<models::InodeMembers>,
}

impl ListResponse {
    pub fn new(parents: Vec<models::InodeMembers>, children: Vec<models::InodeMembers>) -> ListResponse {
        ListResponse {
            parents,
            children,
        }
    }
}

