/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Member {
    /// The database id of the member
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sub")]
    pub sub: String,
    /// The database id of the inode
    #[serde(rename = "inodeId")]
    pub inode_id: String,
    #[serde(rename = "permission")]
    pub permission: f64,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl Member {
    pub fn new(id: String, sub: String, inode_id: String, permission: f64, created_at: String, updated_at: String) -> Member {
        Member {
            id,
            sub,
            inode_id,
            permission,
            created_at,
            updated_at,
        }
    }
}

