/*
 * dabih-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveTokenRequest {
    #[serde(rename = "tokenId")]
    pub token_id: f64,
}

impl RemoveTokenRequest {
    pub fn new(token_id: f64) -> RemoveTokenRequest {
        RemoveTokenRequest {
            token_id,
        }
    }
}

