/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveTokenRequest {
    #[serde(rename = "tokenId")]
    pub token_id: String,
}

impl RemoveTokenRequest {
    pub fn new(token_id: String) -> RemoveTokenRequest {
        RemoveTokenRequest {
            token_id,
        }
    }
}

