/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFs200Response {
    #[serde(rename = "jobId")]
    pub job_id: String,
}

impl SearchFs200Response {
    pub fn new(job_id: String) -> SearchFs200Response {
        SearchFs200Response {
            job_id,
        }
    }
}

