/*
 * dabih-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFs200Response {
    #[serde(rename = "jobId")]
    pub job_id: String,
}

impl SearchFs200Response {
    pub fn new(job_id: String) -> SearchFs200Response {
        SearchFs200Response {
            job_id,
        }
    }
}

