/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.0.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetAccessBody {
    /// The user to set the permission for
    #[serde(rename = "sub")]
    pub sub: String,
    /// The permission to set
    #[serde(rename = "permission")]
    pub permission: f64,
}

impl SetAccessBody {
    pub fn new(sub: String, permission: f64) -> SetAccessBody {
        SetAccessBody {
            sub,
            permission,
        }
    }
}

