/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.0.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignInRequest {
    #[serde(rename = "email")]
    pub email: String,
}

impl SignInRequest {
    pub fn new(email: String) -> SignInRequest {
        SignInRequest {
            email,
        }
    }
}

