/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TokenResponseAllOfExpired : false if the token has not expired, otherwise a string describing how long ago the token expired
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenResponseAllOfExpired {
}

impl TokenResponseAllOfExpired {
    /// false if the token has not expired, otherwise a string describing how long ago the token expired
    pub fn new() -> TokenResponseAllOfExpired {
        TokenResponseAllOfExpired {
        }
    }
}

