/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TsPseudoBigInt : Represents a bigint literal value without requiring bigint support
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TsPseudoBigInt {
    #[serde(rename = "negative")]
    pub negative: bool,
    #[serde(rename = "base10Value")]
    pub base10_value: String,
}

impl TsPseudoBigInt {
    /// Represents a bigint literal value without requiring bigint support
    pub fn new(negative: bool, base10_value: String) -> TsPseudoBigInt {
        TsPseudoBigInt {
            negative,
            base10_value,
        }
    }
}

