/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.0.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserResponse {
    /// The database id of the user
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<serde_json::Value>,
    /// The unique user sub
    #[serde(rename = "sub")]
    pub sub: String,
    /// The email of the user
    #[serde(rename = "email")]
    pub email: String,
    /// the list of scopes the user has
    #[serde(rename = "scope")]
    pub scope: String,
    /// The time of the last authentication
    #[serde(rename = "lastAuthAt")]
    pub last_auth_at: String,
    /// The date the user was created
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The date the user was last updated
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    /// The public keys of the user
    #[serde(rename = "keys")]
    pub keys: Vec<models::PublicKey>,
}

impl UserResponse {
    pub fn new(id: Option<serde_json::Value>, sub: String, email: String, scope: String, last_auth_at: String, created_at: String, updated_at: String, keys: Vec<models::PublicKey>) -> UserResponse {
        UserResponse {
            id,
            sub,
            email,
            scope,
            last_auth_at,
            created_at,
            updated_at,
            keys,
        }
    }
}

