/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.0.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSub {
    #[serde(rename = "sub")]
    pub sub: String,
}

impl UserSub {
    pub fn new(sub: String) -> UserSub {
        UserSub {
            sub,
        }
    }
}

