/*
 * dabih-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAddBody {
    /// The unique user sub if undefined the sub from the auth token will be used
    #[serde(rename = "sub", skip_serializing_if = "Option::is_none")]
    pub sub: Option<String>,
    /// The name of the user
    #[serde(rename = "name")]
    pub name: String,
    /// The email of the user
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "key")]
    pub key: models::CryptoPeriodJsonWebKey,
    /// If true the key is a root key, used to decrypt all datasets
    #[serde(rename = "isRootKey", skip_serializing_if = "Option::is_none")]
    pub is_root_key: Option<bool>,
}

impl UserAddBody {
    pub fn new(name: String, email: String, key: models::CryptoPeriodJsonWebKey) -> UserAddBody {
        UserAddBody {
            sub: None,
            name,
            email,
            key,
            is_root_key: None,
        }
    }
}

