/*
 * dabih-api
 *
 * Dabih API Server
 *
 * The version of the OpenAPI document: 2.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyEmailRequest {
    #[serde(rename = "token")]
    pub token: String,
}

impl VerifyEmailRequest {
    pub fn new(token: String) -> VerifyEmailRequest {
        VerifyEmailRequest {
            token,
        }
    }
}

