
name: Publish Crates.io cli crate

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Copy spec
        run: cp ./api/build/spec.json ./cli/spec.json
      - name: Cargo publish
        working-directory: ./cli
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
